"""OpenAI helpers for premium follow-up questions and essay guidance."""

from __future__ import annotations

import json
import os
from typing import Any

from openai import OpenAI

MODEL = os.environ.get("OPENAI_MODEL", "gpt-4o-mini")

# Structured extracurriculars question. Always appended server-side to the AI
# follow-up set so the GUI is deterministic (not generated by the model).
ACTIVITIES_QUESTION_ID = "ai_activities"
ACTIVITIES_QUESTION = {
    "id": ACTIVITIES_QUESTION_ID,
    "section": "premium",
    "type": "activities",
    "text": "List the extracurriculars and awards you've earned in high school.",
    "placeholder": (
        "Clubs, sports, research, jobs, volunteering, competitions — plus any "
        "awards with their level and year."
    ),
}


def _client() -> OpenAI | None:
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        return None
    return OpenAI(api_key=api_key)


def _chat_json(system: str, user: str) -> dict | list | None:
    client = _client()
    if client is None:
        return None
    response = client.chat.completions.create(
        model=MODEL,
        temperature=0.7,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
    )
    content = response.choices[0].message.content or "{}"
    return json.loads(content)


def generate_followup_questions(profile: dict, prior_answers: dict) -> dict[str, Any]:
    """Return ~4 MCQs and ~2 written prompts tailored to the student."""
    system = (
        "You generate college-major quiz follow-up questions. "
        "Respond with JSON: {"
        '"mcq": [{"id": "ai_mcq_1", "text": "...", "options": '
        '[{"id": "a", "label": "..."}, {"id": "b", "label": "..."}, '
        '{"id": "c", "label": "..."}, {"id": "d", "label": "..."}]}], '
        '"written": [{"id": "ai_written_1", "text": "...", "placeholder": "..."}]}'
        ". Create 4 multiple-choice and 2 short written questions that dig deeper "
        "into interests, extracurriculars, and personality based on prior answers. "
        "Do not include scoring weights."
    )
    user = json.dumps({"profile": profile, "prior_answers": prior_answers})
    result = _chat_json(system, user)
    if result and isinstance(result, dict) and result.get("mcq"):
        return result
    return _fallback_followup()


def _activities_from(answers: dict | None) -> dict:
    """Extract the structured extracurricular payload from raw quiz answers."""
    raw = (answers or {}).get(ACTIVITIES_QUESTION_ID)
    if isinstance(raw, dict):
        return {
            "activities": raw.get("activities") or [],
            "awards": raw.get("awards") or [],
        }
    return {"activities": [], "awards": []}


def _ai_written(answers: dict | None) -> dict:
    """Free-text answers to AI follow-ups (everything ai_* that is a string)."""
    out = {}
    for k, v in (answers or {}).items():
        if str(k).startswith("ai_") and isinstance(v, str) and v.strip():
            out[k] = v.strip()
    return out


def generate_essay_guidance(
    profile: dict, matches: list[dict], answers: dict | None = None
) -> list[dict]:
    """Per-university essay approach tips grounded in the student profile."""
    schools = []
    seen = set()
    for m in matches:
        uni = m.get("university")
        if not uni or uni in seen:
            continue
        seen.add(uni)
        schools.append(
            {
                "university": uni,
                "major": m.get("major"),
                "ranking": m.get("ranking"),
            }
        )

    system = (
        "You are a college admissions essay coach. Respond with JSON: "
        '{"guidance": [{"university": "...", "prompt_themes": ["..."], '
        '"approach": "...", "hooks": ["..."]}]}'
        ". For each school, invent plausible supplemental/essay themes "
        "(Why Us, intellectual curiosity, community, etc.) and explain how THIS "
        "student should approach them using their profile. Be specific and actionable. "
        "When the student lists extracurriculars or awards, reference them by name in "
        "the hooks. Keep approach to 2-3 short paragraphs."
    )
    user = json.dumps(
        {
            "profile": profile,
            "schools": schools,
            "extracurriculars": _activities_from(answers),
            "written_answers": _ai_written(answers),
        }
    )
    result = _chat_json(system, user)
    if result and isinstance(result, dict) and result.get("guidance"):
        return result["guidance"]
    return _fallback_essay_guidance(schools, profile)


ESSAY_PROMPT_MAX = 2000
ESSAY_RESPONSE_MAX = 10000
RUBRIC_CATEGORIES = ["Prompt fit", "Specificity", "Voice & authenticity", "Structure", "Mechanics"]


def grade_essay(
    profile: dict,
    answers: dict | None,
    program: dict,
    prompt: str,
    response: str,
) -> dict:
    """Grade an essay draft and suggest voice-preserving fixes.

    Returns a dict shaped like:
    {
      "overall_score": 0-100,
      "rubric": [{"name", "score" (1-10), "comment"}],
      "style_profile": "...",
      "strengths": ["..."],
      "suggestions": [{"quote", "issue", "rewrite", "why"}],
      "prompt_fit": "..."
    }
    """
    system = (
        "You are an expert college admissions essay coach and editor. You will receive "
        "a student's quiz profile (interest vector, academic strength, preferences), "
        "their written answers, a structured list of their extracurriculars and awards, "
        "the program they are applying to, the essay prompt, and their draft response.\n\n"
        "FIRST, silently infer the student's writing style from the draft: typical "
        "sentence length and rhythm, vocabulary level, tone (earnest, wry, plain, lyrical), "
        "use of dialogue or imagery, and paragraph habits. EVERY rewrite you propose MUST "
        "sound like the student wrote it — same register, same vocabulary level, no "
        "thesaurus upgrades, no generic 'admissions-speak'. Prefer the smallest edit that "
        "fixes the problem. Never invent facts; when a passage would benefit from a concrete "
        "detail, pull it from the student's listed extracurriculars, awards, or written "
        "answers, and if none fit, describe what kind of detail to add in the 'why' field "
        "instead of fabricating one.\n\n"
        "Respond ONLY with JSON: {"
        '"overall_score": <integer 0-100>, '
        '"rubric": [{"name": "Prompt fit"|"Specificity"|"Voice & authenticity"|"Structure"|"Mechanics", '
        '"score": <integer 1-10>, "comment": "<one or two sentences>"}], '
        '"style_profile": "<2-3 sentences describing the student\'s voice>", '
        '"strengths": ["<specific strength>", ...], '
        '"suggestions": [{"quote": "<exact excerpt from the draft, <= 40 words>", '
        '"issue": "<what is weak>", "rewrite": "<replacement text in the student\'s voice>", '
        '"why": "<how this helps for THIS program/prompt>"}], '
        '"prompt_fit": "<2-3 sentences on how well the draft answers the prompt and fits the program>"'
        "}. Include all five rubric categories exactly once. Give 3-6 suggestions ordered by "
        "impact. Quotes must be verbatim substrings of the draft so they can be located."
    )
    user = json.dumps(
        {
            "program": {
                "university": program.get("university"),
                "major": program.get("major"),
                "college": program.get("college"),
                "description": (program.get("description") or "")[:600],
            },
            "profile": {
                "interest": profile.get("interest"),
                "strength": profile.get("strength"),
                "prefs": profile.get("prefs"),
            },
            "written_answers": _ai_written(answers),
            "extracurriculars": _activities_from(answers),
            "essay_prompt": prompt[:ESSAY_PROMPT_MAX],
            "draft": response[:ESSAY_RESPONSE_MAX],
        }
    )
    result = _chat_json(system, user)
    if result and isinstance(result, dict) and result.get("rubric"):
        return _normalize_feedback(result)
    return _fallback_essay_feedback(program, prompt, response)


def _normalize_feedback(raw: dict) -> dict:
    rubric = []
    for item in raw.get("rubric") or []:
        if not isinstance(item, dict):
            continue
        try:
            score = int(round(float(item.get("score", 0))))
        except (TypeError, ValueError):
            score = 0
        rubric.append(
            {
                "name": str(item.get("name", "")).strip() or "Criterion",
                "score": max(1, min(10, score)),
                "comment": str(item.get("comment", "")).strip(),
            }
        )
    try:
        overall = int(round(float(raw.get("overall_score", 0))))
    except (TypeError, ValueError):
        overall = 0
    if overall <= 0 and rubric:
        overall = int(round(sum(r["score"] for r in rubric) / len(rubric) * 10))
    suggestions = []
    for s in raw.get("suggestions") or []:
        if not isinstance(s, dict):
            continue
        suggestions.append(
            {
                "quote": str(s.get("quote", "")).strip(),
                "issue": str(s.get("issue", "")).strip(),
                "rewrite": str(s.get("rewrite", "")).strip(),
                "why": str(s.get("why", "")).strip(),
            }
        )
    return {
        "overall_score": max(0, min(100, overall)),
        "rubric": rubric,
        "style_profile": str(raw.get("style_profile", "")).strip(),
        "strengths": [str(x).strip() for x in (raw.get("strengths") or []) if str(x).strip()],
        "suggestions": suggestions,
        "prompt_fit": str(raw.get("prompt_fit", "")).strip(),
    }


def _fallback_essay_feedback(program: dict, prompt: str, response: str) -> dict:
    """Heuristic feedback when OpenAI is unavailable, so the UI still works."""
    words = response.split()
    n_words = len(words)
    sentences = [s for s in response.replace("!", ".").replace("?", ".").split(".") if s.strip()]
    avg_len = (n_words / len(sentences)) if sentences else 0
    uni = program.get("university") or "this school"
    mentions_school = bool(uni and uni.lower() in response.lower())
    rubric = [
        {
            "name": "Prompt fit",
            "score": 7 if mentions_school else 5,
            "comment": (
                "You name the school directly." if mentions_school
                else f"The draft never names {uni} or a specific program resource — tie it to the prompt explicitly."
            ),
        },
        {
            "name": "Specificity",
            "score": 6 if n_words > 200 else 4,
            "comment": "Add one concrete scene with names, numbers, or a moment that only you could describe.",
        },
        {
            "name": "Voice & authenticity",
            "score": 7,
            "comment": "Keep sentences in your natural register; cut any phrase you would not say aloud.",
        },
        {
            "name": "Structure",
            "score": 6 if 12 <= avg_len <= 24 else 5,
            "comment": (
                "Sentence length is in a readable range." if 12 <= avg_len <= 24
                else "Vary sentence length: mix one short punchy line into each paragraph."
            ),
        },
        {
            "name": "Mechanics",
            "score": 7,
            "comment": "Read the draft aloud once to catch tense shifts and run-ons.",
        },
    ]
    overall = int(round(sum(r["score"] for r in rubric) / len(rubric) * 10))
    first_sentence = (sentences[0].strip() + ".") if sentences else ""
    return {
        "overall_score": overall,
        "rubric": rubric,
        "style_profile": (
            f"About {n_words} words with an average of {avg_len:.0f} words per sentence. "
            "Automatic feedback is limited while the AI service is unavailable."
        ),
        "strengths": ["You finished a full draft — that is the hardest part."],
        "suggestions": [
            {
                "quote": first_sentence[:200],
                "issue": "Openings that summarize tend to read flat.",
                "rewrite": "",
                "why": "Start inside a specific moment instead of a summary, then zoom out.",
            }
        ] if first_sentence else [],
        "prompt_fit": f"Make sure the draft answers the prompt directly and names why {uni} in particular.",
    }


def _fallback_followup() -> dict[str, Any]:
    return {
        "mcq": [
            {
                "id": "ai_mcq_1",
                "text": "When a project hits a wall, what do you do first?",
                "options": [
                    {"id": "a", "label": "Break the problem into smaller pieces and test each one"},
                    {"id": "b", "label": "Talk it through with someone who sees it differently"},
                    {"id": "c", "label": "Look for examples of how others solved something similar"},
                    {"id": "d", "label": "Step away and return with fresh eyes"},
                ],
            },
            {
                "id": "ai_mcq_2",
                "text": "Which kind of recognition means the most to you?",
                "options": [
                    {"id": "a", "label": "Being known as the go-to expert on something hard"},
                    {"id": "b", "label": "Leading a team that ships something people use"},
                    {"id": "c", "label": "Creating work that moves or persuades others"},
                    {"id": "d", "label": "Quietly improving a system that helps many people"},
                ],
            },
            {
                "id": "ai_mcq_3",
                "text": "Pick the elective you'd take just because it sounds fascinating.",
                "options": [
                    {"id": "a", "label": "How algorithms shape everyday decisions"},
                    {"id": "b", "label": "The science of how people form habits"},
                    {"id": "c", "label": "Designing products people actually love"},
                    {"id": "d", "label": "Stories that changed how societies think"},
                ],
            },
            {
                "id": "ai_mcq_4",
                "text": "In a group project, which role feels most natural?",
                "options": [
                    {"id": "a", "label": "The builder who owns the technical core"},
                    {"id": "b", "label": "The organizer who keeps everyone aligned"},
                    {"id": "c", "label": "The researcher who digs up what others miss"},
                    {"id": "d", "label": "The presenter who makes the story land"},
                ],
            },
        ],
        "written": [
            {
                "id": "ai_written_1",
                "text": "Describe one activity or project that best shows how you think. What did you do, and what did you learn?",
                "placeholder": "2–4 sentences",
            },
            {
                "id": "ai_written_2",
                "text": "What question about the world do you keep coming back to — and why does it matter to you?",
                "placeholder": "2–4 sentences",
            },
        ],
    }


def _fallback_essay_guidance(schools: list[dict], profile: dict) -> list[dict]:
    top_interests = sorted(
        (profile.get("interest") or {}).items(), key=lambda x: x[1], reverse=True
    )[:3]
    interest_labels = [k.replace("_", " ") for k, _ in top_interests] or ["your strongest interests"]
    hooks = [
        f"Lead with a concrete moment tied to {interest_labels[0]}.",
        "Connect one extracurricular to a specific campus opportunity.",
        "Show how you collaborate and what you want to build next.",
    ]
    out = []
    for s in schools:
        out.append(
            {
                "university": s["university"],
                "prompt_themes": [
                    f"Why {s['university']}?",
                    "Intellectual curiosity / academic interest",
                    "Community contribution",
                ],
                "approach": (
                    f"For {s['university']}, anchor your story in {', '.join(interest_labels)}. "
                    f"If you're drawn to {s.get('major', 'this program')}, explain a specific "
                    "experience that made that interest feel real — not a résumé list. "
                    "Then name one resource, lab, or community at the school you'd use, and "
                    "close with what you'd contribute back."
                ),
                "hooks": hooks,
            }
        )
    return out
